version: "2"

run:
  timeout: 2m
  tests: false

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - unused
    - gofmt
    - goimports
    - revive
    - gocritic
    - ineffassign
    - typecheck
    - misspell
    - unparam
    - nakedret
    - prealloc
    - gocyclo
    - dupl
    - dogsled
    - exportloopref
    - goconst
    - gocognit
    - godot
    - godox
    - nolintlint
    - whitespace
    - forbidigo
    - forbidigo
    - lll
    - stylecheck
    - gosec
    - asasalint
    - bodyclose
    - durationcheck
    - errorlint
    - exhaustive
    - forbidigo
    - gci
    - goerr113
    - gomnd
    - goprintffuncname
    - gosec
    - importas
    - makezero
    - nestif
    - noctx
    - predeclared
    - rowserrcheck
    - sqlclosecheck
    - testpackage
    - thelper
    - tparallel
    - wastedassign
    - zerologlint

  settings:
    gocyclo:
      min-complexity: 15
    lll:
      line-length: 120

formatters:
  settings:
    gofmt:
      simplify: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0